---
server:
  port: 8080
  contextPath: /pruebadish
---
spring:
  profiles: default
  active: default
  h2:
    console:
      enabled: true
datasource:
  pruebadish:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
  active: prod
datasource:
  pruebadish:
    url: jdbc:mysql://localhost:3306/pruebadish
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect



